# Checkmarx Documentation can be found at:
#  https://docs.checkmarx.com/en/34965-68702-checkmarx-one-github-actions.html
# The additional_params field, you can specify any CLI arguments that you would like to apply to scans of this project.
name: Checkmarx One - With Security report
on:
  pull_request:
  #  types:
  #   - opened
  #    - closed
    branches:
      - main
  workflow_dispatch:
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:   
      - name: Check Paths ${{ github.workspace }}
        run: ls ${{ github.runner_temp }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@749fec53e0db0f6404a97e2e0807c3e80e3583a7
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net/
          # Provide the Tenant for AST portal URL
          cx_tenant: ${{ secrets.CXONE_TENANT }}
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CXONE_CLIENTID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CXONE_CLIENTSECRET }}
          # Select a Checkmarx Project Name
          # optional, default is ${{ github.repository }}
          project_name: ${{ github.repository }}
          # Branch name
          # optional, default is ${{ github.head_ref || github.ref }}
          branch: ${{ github.head_ref || github.ref }}
          # GitHub API Token
          # optional, default is ${{ github.token }}
          github_token: ${{ secrets.PR_TOKEN }}
          # Additional parameters for AST scan
          additional_params: --sast-preset-name "ASA Premium" --threshold "sast-high=10; sast-medium=20; sca-high=10; containers-high=5" --report-format sarif --output-path "./"
          # optional, default is ${{ github.event.repository.name }}
          repo_name: ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          # optional, default is ${{ github.repository_owner }}
          namespace: ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          # optional, default is ${{ github.event.number }}
          pr_number: ${{ github.event.number }}
      - name: Check Paths
        run: pwd && ls
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  if:  always()
      #  #if: ${{ hashFiles('${{ github.runner_temp }}/cx_result.sarif') != '' }}
      #  with: 
      #    # Path to SARIF file relative to the root of the repository
      #    sarif_file: "${{ github.runner_temp }}/cx_result.sarif"
      #    category: cxone-analysis
                
